from fastapi import FastAPI, HTTPException
import pandas as pd
from contextlib import asynccontextmanager

# Global dictionary to hold pre-calculated customer data for O(1) instant lookups
rfm_db = {}

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Loads the pre-calculated data into memory when the server starts.
    This guarantees that API endpoints respond instantly.
    """
    try:
        print("Loading RFM data into memory...")
        # Load the CSV generated by your heavy Pandas script
        df = pd.read_csv('rfm_output.csv')
        
        # Convert it to a dictionary for ultra-fast key-value lookups
        global rfm_db
        rfm_db = df.set_index('customer_unique_id').to_dict(orient='index')
        print(f"Successfully loaded data for {len(rfm_db)} unique customers.")
    except FileNotFoundError:
        print("WARNING: 'rfm_output.csv' not found! Please run 'compute_rfm.py' first.")
    
    yield
    # Clean up operations (if any) can go here when the server shuts down
    rfm_db.clear()

# Initialize FastAPI with the lifespan context manager
app = FastAPI(
    title="Customer RFM Segmentation API",
    description="Serves pre-calculated customer segments and data-driven marketing recommendations.",
    version="1.0.0",
    lifespan=lifespan
)

@app.get("/")
def home():
    return {"message": "RFM Segmentation API is online. Go to /docs for the Swagger UI."}

@app.get("/api/v1/customer-segment/{customer_unique_id}")
def get_customer_segment(customer_unique_id: str):
    """
    Fetches the RFM scores, segment name, and provides an actionable marketing strategy.
    """
    # Quick key lookup in our in-memory dictionary
    customer_data = rfm_db.get(customer_unique_id)
    
    if not customer_data:
        raise HTTPException(
            status_code=404,
            detail=f"Customer ID '{customer_unique_id}' not found in the database."
        )
    
    segment = customer_data['Customer_Segment']
    
    # Dynamic, automated business recommendations based on the segment
    marketing_strategies = {
        'Champions': "Do not give them discounts. Offer them early access to new product lines and premium loyalty rewards.",
        'Loyal Customers': "Upsell higher-value items. Ask for reviews or case studies to leverage their brand loyalty.",
        'Potential Loyalist': "Offer a second-purchase incentive or recommend complementary products to build buying habits.",
        'Recent Customers': "Send a welcome onboarding sequence or a simple customer satisfaction feedback survey.",
        'Promising': "Provide limited-time offers to create a sense of urgency and nudge them into a repeat purchase.",
        'Needs Attention': "Send personalized recommendations based on past purchases before they drift away.",
        'At Risk': "Send highly personalized win-back emails with high-value renewal discounts.",
        'Hibernating': "Offer massive clearance discounts or standard re-engagement campaigns.",
        'Lost': "Attempt a final cheap reactivation offer, otherwise remove from regular marketing distribution lists to save costs."
    }
    
    # Fallback if a segment isn't explicitly defined in our strategy map
    strategy = marketing_strategies.get(segment, "Standard promotional newsletter distribution.")
    
    return {
        "customer_id": customer_unique_id,
        "rfm_scores": {
            "recency_score": int(customer_data['R_score']),
            "frequency_score": int(customer_data['F_score']),
            "monetary_score": int(customer_data['M_score'])
        },
        "segment_code": str(customer_data['RFM_Segment']),
        "segment_name": segment,
        "recommended_action": strategy
    }
